version: '3'

services:
  springboot-mysql:
    image: kevpin/springboot-mysql
    ports:
      - 9092:8086
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/mysqldemo?autoReconnect=true&useSSL=false
    depends_on:
      - mysql-standalone
  mysql-standalone:
    image: mysql:5.6
    container_name: mysql-standalone
    ports:
      - 3307:3306
    environment:
        MYSQL_DATABASE: mysqldemo
        MYSQL_USER: sa
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
